database {
    enabled = true
    enabled = ${?DB_ENABLED}
    host = "localhost"
    host = ${?DB_HOST}
    port = 5432
    port = ${?DB_PORT}
    name = "defenderofegril"
    name = ${?DB_NAME}
    user = "defender"
    user = ${?DB_USER}
    password = "defender"
    password = ${?DB_PASSWORD}
}
