package de.egril.defender.ui.editor.map

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.lazy.grid.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import de.egril.defender.editor.EditorMap
import de.egril.defender.editor.EditorStorage
import de.egril.defender.save.CommunityFileInfo
import de.egril.defender.ui.editor.CreateMapDialog
import com.hyperether.resources.stringResource
import defender_of_egril.composeapp.generated.resources.*
import kotlin.random.Random
import androidx.compose.ui.graphics.painter.Painter
import androidx.compose.ui.graphics.painter.BitmapPainter
import de.egril.defender.ui.MapImageProvider
import de.egril.defender.iam.IamService
import de.egril.defender.ui.editor.getDefaultAuthorName
import de.egril.defender.ui.icon.CheckmarkIcon
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

/**
 * Returns all maps visible in the map editor: user/official maps plus community maps.
 * Community maps appear last, sorted by name.
 */
private fun allMapsForEditor(): List<EditorMap> {
    val userAndOfficialMaps = EditorStorage.getAllMaps()
    val communityMaps = EditorStorage.getAllCommunityMaps()
        .filter { cm -> userAndOfficialMaps.none { it.id == cm.id } }  // skip maps already present locally
    return userAndOfficialMaps + communityMaps
}

/**
 * Main content for the Map Editor tab
 *
 * @param remoteCommunityMaps Community maps available on the server (not yet downloaded locally)
 * @param downloadingMapId The fileId of a community map currently being downloaded, or null
 * @param onDownloadRemoteMap Callback to trigger on-demand download of a remote-only map
 */
@Composable
fun MapEditorContent(
    remoteCommunityMaps: List<CommunityFileInfo> = emptyList(),
    downloadingMapId: String? = null,
    onDownloadRemoteMap: ((CommunityFileInfo) -> Unit)? = null
) {
    val maps = remember { mutableStateOf(allMapsForEditor()) }
    var selectedMapId by remember { mutableStateOf<String?>(null) }
    var editingMap by remember { mutableStateOf<EditorMap?>(null) }
    var showCreateDialog by remember { mutableStateOf(false) }
    val coroutineScope = rememberCoroutineScope()
    val iamState by IamService.state

    var showGenerationDialog by remember { mutableStateOf(false) }
    var generationRunning by remember { mutableStateOf(false) }
    var generationSuccess by remember { mutableStateOf<Boolean?>(null) }
    var generationError by remember { mutableStateOf<String?>(null) }
    var generatedPainter by remember { mutableStateOf<Painter?>(null) }
    var showPreview by remember { mutableStateOf(false) }
    var generatorMapName by remember { mutableStateOf("") }
    var generatorTargetPath by remember { mutableStateOf("") }
    var imageWasRegenerated by remember { mutableStateOf(true) }
    // Two-step progress tracking
    var generationStep by remember { mutableStateOf("") }  // "generating", "compressing", ""
    var compressedSizeKb by remember { mutableStateOf(0L) }

    // IDs of locally-downloaded community maps – used to suppress remote-only entries that are already available locally
    val localCommunityMapIds = remember(maps.value) {
        maps.value.filter { it.isCommunity }.map { it.id }.toSet()
    }
    // Remote-only maps: server has them but they are not yet downloaded locally
    val remoteOnlyMaps = remember(remoteCommunityMaps, localCommunityMapIds) {
        remoteCommunityMaps.filter { it.fileId !in localCommunityMapIds }
    }

    // Refresh the map list when a download finishes (downloadingMapId transitions from non-null to null)
    var prevDownloadingMapId by remember { mutableStateOf(downloadingMapId) }
    LaunchedEffect(downloadingMapId) {
        val prev = prevDownloadingMapId
        prevDownloadingMapId = downloadingMapId
        if (prev != null && downloadingMapId == null) {
            maps.value = allMapsForEditor()
        }
    }

    fun targetPath(map: EditorMap): String {
        return if (map.isOfficial) {
            "gamedata/official/maps/${map.id}.png"
        } else {
            "gamedata/user/maps/${map.id}.png"
        }
    }

    fun handleSave(mapToSave: EditorMap, oldId: String? = null) {
        generatorMapName = mapToSave.name
        generatorTargetPath = targetPath(mapToSave)
        showGenerationDialog = true
        showPreview = false
        generationRunning = true
        generationSuccess = null
        generationError = null
        generatedPainter = null
        imageWasRegenerated = true
        generationStep = ""
        compressedSizeKb = 0L

        coroutineScope.launch {
            try {
                // Step 1: Save map JSON data and decide whether image needs regeneration
                val saveResult = withContext(Dispatchers.Default) {
                    EditorStorage.saveMapData(mapToSave, oldId)
                }

                if (saveResult.imageNeedsRegeneration) {
                    // Step 2: Generate map image pixels
                    generationStep = "generating"
                    val (pixels, width, height) = withContext(Dispatchers.Default) {
                        EditorStorage.generateMapPixels(saveResult.validatedMap)
                    }

                    // Step 3: Compress to PNG and save
                    generationStep = "compressing"
                    val sizeBytes = withContext(Dispatchers.Default) {
                        EditorStorage.compressAndSaveMapImage(saveResult.validatedMap, pixels, width, height)
                    }
                    compressedSizeKb = if (sizeBytes > 0) sizeBytes / 1024 else 0L
                } else {
                    imageWasRegenerated = false
                }

                generationStep = ""
                generationSuccess = true
                maps.value = allMapsForEditor()
                editingMap = null
                val bytes = MapImageProvider.loadMapImageBytes(mapToSave.id)
                val bitmap = bytes?.let { MapImageProvider.decodeImageBitmap(it) }
                generatedPainter = bitmap?.let { BitmapPainter(it) }
            } catch (e: Exception) {
                generationSuccess = false
                generationError = e.message
            } finally {
                generationRunning = false
                generationStep = ""
            }
        }
    }
    
    if (editingMap != null) {
        // Map editing view
        MapEditorView(
            map = editingMap!!,
            onSave = { updatedMap, oldId -> handleSave(updatedMap, oldId) },
            onCancel = { editingMap = null }
        )
    } else {
        // Map list view
        Column(
            modifier = Modifier.fillMaxWidth()
        ) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text(
                    text = stringResource(Res.string.maps),
                    style = MaterialTheme.typography.titleMedium,
                    modifier = Modifier.padding(bottom = 8.dp)
                )
                
                Button(onClick = { showCreateDialog = true }) {
                    Text(stringResource(Res.string.create_new_map))
                }
            }
            
            Text(
                text = stringResource(Res.string.select_map_to_edit),
                style = MaterialTheme.typography.bodyMedium,
                modifier = Modifier.padding(bottom = 8.dp)
            )
            
            LazyVerticalGrid(
                columns = GridCells.Adaptive(minSize = 400.dp),
                modifier = Modifier.fillMaxWidth().weight(1f),
                verticalArrangement = Arrangement.spacedBy(8.dp),
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                // Locally-available maps (official + user + already-downloaded community)
                items(maps.value) { map ->
                    MapListCard(
                        map = map,
                        isSelected = selectedMapId == map.id,
                        onSelect = {
                            selectedMapId = map.id
                            editingMap = map
                        },
                        onDelete = {
                            EditorStorage.deleteMap(map.id)
                            maps.value = allMapsForEditor()
                        },
                        onCopy = {
                            // Create a copy with a new ID
                            val sanitizedName = map.name.trim().lowercase()
                                .replace(" ", "_")
                                .replace(Regex("[^a-z0-9_]"), "")
                                .replace(Regex("_+"), "_")
                            val copyId = if (sanitizedName.isNotEmpty()) {
                                "map_${sanitizedName}_copy_${Random.nextInt(1000, 9999)}"
                            } else {
                                "map_${map.id}_copy_${Random.nextInt(1000, 9999)}"
                            }
                            val copiedMap = map.copy(
                                id = copyId,
                                name = "${map.name} (Copy)",
                                isOfficial = false  // Copied maps are never official
                            )
                            // Copy the existing PNG image instead of regenerating it
                            EditorStorage.copyMap(map, copiedMap)
                            maps.value = allMapsForEditor()
                            selectedMapId = copyId
                            editingMap = copiedMap
                        }
                    )
                }
                // Remote-only community maps
                items(remoteOnlyMaps) { fileInfo ->
                    RemoteCommunityMapCard(
                        fileInfo = fileInfo,
                        isDownloading = fileInfo.fileId == downloadingMapId,
                        onDownload = {
                            onDownloadRemoteMap?.invoke(fileInfo)
                        }
                    )
                }
            }
        }
    }
    
    if (showCreateDialog) {
        val defaultAuthor = getDefaultAuthorName(iamState)
        CreateMapDialog(
            onDismiss = { showCreateDialog = false },
            defaultAuthor = defaultAuthor,
            onCreate = { name, width, height, author ->
                // Generate ID from name with underscores (lowercase)
                val sanitizedName = name.trim().lowercase()
                    .replace(" ", "_")
                    .replace(Regex("[^a-z0-9_]"), "")
                    .replace(Regex("_+"), "_")  // Collapse consecutive underscores
                val newId = if (sanitizedName.isNotEmpty()) {
                    "map_$sanitizedName"
                } else {
                    "map_custom_${Random.nextInt(10000, 99999)}"
                }
                val newMap = EditorMap(
                    id = newId,
                    name = name,
                    width = width,
                    height = height,
                    tiles = emptyMap(),
                    author = author
                )
                EditorStorage.saveMap(newMap)
                maps.value = allMapsForEditor()
                showCreateDialog = false
                editingMap = newMap
            }
        )
    }

    if (showGenerationDialog) {
        AlertDialog(
            onDismissRequest = {
                if (!generationRunning) {
                    showGenerationDialog = false
                }
            },
            title = {
                Text(stringResource(Res.string.map_image_generation_title, generatorMapName))
            },
            text = {
                Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                    Text(stringResource(Res.string.map_image_generation_path, generatorTargetPath))

                    when {
                        generationRunning -> {
                            Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                                // Step 1: Generating pixels
                                Row(
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                                ) {
                                    if (generationStep == "generating") {
                                        CircularProgressIndicator(modifier = Modifier.size(20.dp), strokeWidth = 2.dp)
                                    } else if (generationStep == "compressing") {
                                        CheckmarkIcon(size = 20.dp, tint = MaterialTheme.colorScheme.primary)
                                    }
                                    Text(stringResource(Res.string.map_image_generation_running))
                                }
                                // Step 2: Compressing (shown only when reached)
                                if (generationStep == "compressing") {
                                    Row(
                                        verticalAlignment = Alignment.CenterVertically,
                                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                                    ) {
                                        CircularProgressIndicator(modifier = Modifier.size(20.dp), strokeWidth = 2.dp)
                                        Text(stringResource(Res.string.map_image_compressing))
                                    }
                                }
                            }
                        }
                        generationSuccess == true -> {
                            if (imageWasRegenerated) {
                                Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
                                    Row(
                                        verticalAlignment = Alignment.CenterVertically,
                                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                                    ) {
                                        CheckmarkIcon(size = 20.dp, tint = MaterialTheme.colorScheme.primary)
                                        Text(stringResource(Res.string.map_image_generation_running))
                                    }
                                    Row(
                                        verticalAlignment = Alignment.CenterVertically,
                                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                                    ) {
                                        CheckmarkIcon(size = 20.dp, tint = MaterialTheme.colorScheme.primary)
                                        Text(stringResource(Res.string.map_image_compressing))
                                    }
                                    if (compressedSizeKb > 0) {
                                        Text(
                                            stringResource(Res.string.map_image_compressed_size, compressedSizeKb.toString()),
                                            style = MaterialTheme.typography.bodySmall,
                                            color = MaterialTheme.colorScheme.onSurfaceVariant
                                        )
                                    }
                                }
                            } else {
                                Text(stringResource(Res.string.map_image_already_existed))
                            }
                        }
                        generationSuccess == false -> {
                            Text(stringResource(Res.string.map_image_generation_error, generationError ?: ""))
                        }
                    }

                    if (showPreview && generatedPainter != null) {
                        Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                            Text(stringResource(Res.string.map_image_generation_preview_label))
                            androidx.compose.foundation.Image(
                                painter = generatedPainter!!,
                                contentDescription = null,
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .heightIn(max = 240.dp)
                            )
                        }
                    }
                }
            },
            confirmButton = {
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    val canShowImage = !generationRunning && generationSuccess == true && generatedPainter != null
                    TextButton(
                        onClick = { showPreview = true },
                        enabled = canShowImage
                    ) {
                        Text(stringResource(Res.string.map_image_generation_show_image))
                    }
                    TextButton(onClick = { showGenerationDialog = false }) {
                        Text(stringResource(Res.string.map_image_generation_close))
                    }
                }
            }
        )
    }
}
