package de.egril.defender.ui.editor.map

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.lazy.grid.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import de.egril.defender.editor.EditorMap
import de.egril.defender.editor.EditorStorage
import de.egril.defender.ui.editor.CreateMapDialog
import com.hyperether.resources.stringResource
import defender_of_egril.composeapp.generated.resources.*
import kotlin.random.Random
import androidx.compose.ui.graphics.painter.Painter
import androidx.compose.ui.graphics.painter.BitmapPainter
import de.egril.defender.ui.MapImageProvider
import de.egril.defender.utils.getCurrentUsername
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

/**
 * Main content for the Map Editor tab
 */
@Composable
fun MapEditorContent() {
    val maps = remember { mutableStateOf(EditorStorage.getAllMaps()) }
    var selectedMapId by remember { mutableStateOf<String?>(null) }
    var editingMap by remember { mutableStateOf<EditorMap?>(null) }
    var showCreateDialog by remember { mutableStateOf(false) }
    val coroutineScope = rememberCoroutineScope()

    var showGenerationDialog by remember { mutableStateOf(false) }
    var generationRunning by remember { mutableStateOf(false) }
    var generationSuccess by remember { mutableStateOf<Boolean?>(null) }
    var generationError by remember { mutableStateOf<String?>(null) }
    var generatedPainter by remember { mutableStateOf<Painter?>(null) }
    var showPreview by remember { mutableStateOf(false) }
    var generatorMapName by remember { mutableStateOf("") }
    var generatorTargetPath by remember { mutableStateOf("") }
    var imageWasRegenerated by remember { mutableStateOf(true) }

    fun targetPath(map: EditorMap): String {
        return if (map.isOfficial) {
            "gamedata/official/maps/${map.id}.png"
        } else {
            "gamedata/user/maps/${map.id}.png"
        }
    }

    fun handleSave(mapToSave: EditorMap, oldId: String? = null) {
        generatorMapName = mapToSave.name
        generatorTargetPath = targetPath(mapToSave)
        showGenerationDialog = true
        showPreview = false
        generationRunning = true
        generationSuccess = null
        generationError = null
        generatedPainter = null
        imageWasRegenerated = true

        coroutineScope.launch {
            try {
                val regenerated = withContext(Dispatchers.Default) {
                    EditorStorage.saveMap(mapToSave, oldId)
                }
                imageWasRegenerated = regenerated
                generationSuccess = true
                maps.value = EditorStorage.getAllMaps()
                editingMap = null
                val bytes = MapImageProvider.loadMapImageBytes(mapToSave.id)
                val bitmap = bytes?.let { MapImageProvider.decodeImageBitmap(it) }
                generatedPainter = bitmap?.let { BitmapPainter(it) }
            } catch (e: Exception) {
                generationSuccess = false
                generationError = e.message
            } finally {
                generationRunning = false
            }
        }
    }
    
    if (editingMap != null) {
        // Map editing view
        MapEditorView(
            map = editingMap!!,
            onSave = { updatedMap, oldId -> handleSave(updatedMap, oldId) },
            onCancel = { editingMap = null }
        )
    } else {
        // Map list view
        Column(
            modifier = Modifier.fillMaxWidth()
        ) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text(
                    text = stringResource(Res.string.maps),
                    style = MaterialTheme.typography.titleMedium,
                    modifier = Modifier.padding(bottom = 8.dp)
                )
                
                Button(onClick = { showCreateDialog = true }) {
                    Text(stringResource(Res.string.create_new_map))
                }
            }
            
            Text(
                text = stringResource(Res.string.select_map_to_edit),
                style = MaterialTheme.typography.bodyMedium,
                modifier = Modifier.padding(bottom = 8.dp)
            )
            
            LazyVerticalGrid(
                columns = GridCells.Adaptive(minSize = 400.dp),
                modifier = Modifier.fillMaxWidth().weight(1f),
                verticalArrangement = Arrangement.spacedBy(8.dp),
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                items(maps.value) { map ->
                    MapListCard(
                        map = map,
                        isSelected = selectedMapId == map.id,
                        onSelect = {
                            selectedMapId = map.id
                            editingMap = map
                        },
                        onDelete = {
                            EditorStorage.deleteMap(map.id)
                            maps.value = EditorStorage.getAllMaps()
                        },
                        onCopy = {
                            // Create a copy with a new ID
                            val sanitizedName = map.name.trim().lowercase()
                                .replace(" ", "_")
                                .replace(Regex("[^a-z0-9_]"), "")
                                .replace(Regex("_+"), "_")
                            val copyId = if (sanitizedName.isNotEmpty()) {
                                "map_${sanitizedName}_copy_${Random.nextInt(1000, 9999)}"
                            } else {
                                "map_${map.id}_copy_${Random.nextInt(1000, 9999)}"
                            }
                            val copiedMap = map.copy(
                                id = copyId,
                                name = "${map.name} (Copy)",
                                isOfficial = false  // Copied maps are never official
                            )
                            // Copy the existing PNG image instead of regenerating it
                            EditorStorage.copyMap(map, copiedMap)
                            maps.value = EditorStorage.getAllMaps()
                            selectedMapId = copyId
                            editingMap = copiedMap
                        }
                    )
                }
            }
        }
    }
    
    if (showCreateDialog) {
        CreateMapDialog(
            onDismiss = { showCreateDialog = false },
            onCreate = { name, width, height ->
                // Generate ID from name with underscores (lowercase)
                val sanitizedName = name.trim().lowercase()
                    .replace(" ", "_")
                    .replace(Regex("[^a-z0-9_]"), "")
                    .replace(Regex("_+"), "_")  // Collapse consecutive underscores
                val newId = if (sanitizedName.isNotEmpty()) {
                    "map_$sanitizedName"
                } else {
                    "map_custom_${Random.nextInt(10000, 99999)}"
                }
                val newMap = EditorMap(
                    id = newId,
                    name = name,
                    width = width,
                    height = height,
                    tiles = emptyMap(),
                    author = getCurrentUsername()
                )
                EditorStorage.saveMap(newMap)
                maps.value = EditorStorage.getAllMaps()
                showCreateDialog = false
                editingMap = newMap
            }
        )
    }

    if (showGenerationDialog) {
        AlertDialog(
            onDismissRequest = {
                if (!generationRunning) {
                    showGenerationDialog = false
                }
            },
            title = {
                Text(stringResource(Res.string.map_image_generation_title, generatorMapName))
            },
            text = {
                Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                    Text(stringResource(Res.string.map_image_generation_path, generatorTargetPath))

                    when {
                        generationRunning -> {
                            Row(
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.spacedBy(8.dp)
                            ) {
                                CircularProgressIndicator(modifier = Modifier.size(20.dp), strokeWidth = 2.dp)
                                Text(stringResource(Res.string.map_image_generation_running))
                            }
                        }
                        generationSuccess == true -> {
                            Text(
                                if (imageWasRegenerated) {
                                    stringResource(Res.string.map_image_generation_done)
                                } else {
                                    stringResource(Res.string.map_image_already_existed)
                                }
                            )
                        }
                        generationSuccess == false -> {
                            Text(stringResource(Res.string.map_image_generation_error, generationError ?: ""))
                        }
                    }

                    if (showPreview && generatedPainter != null) {
                        Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                            Text(stringResource(Res.string.map_image_generation_preview_label))
                            androidx.compose.foundation.Image(
                                painter = generatedPainter!!,
                                contentDescription = null,
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .heightIn(max = 240.dp)
                            )
                        }
                    }
                }
            },
            confirmButton = {
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    val canShowImage = !generationRunning && generationSuccess == true && generatedPainter != null
                    TextButton(
                        onClick = { showPreview = true },
                        enabled = canShowImage
                    ) {
                        Text(stringResource(Res.string.map_image_generation_show_image))
                    }
                    TextButton(onClick = { showGenerationDialog = false }) {
                        Text(stringResource(Res.string.map_image_generation_close))
                    }
                }
            }
        )
    }
}
