package de.egril.defender.model

import androidx.compose.runtime.MutableState
import androidx.compose.runtime.mutableStateOf

enum class DefenderType(
    val displayName: String,
    val baseCost: Int,
    val baseDamage: Int,
    val baseRange: Int,
    val attackType: AttackType,
    val actionsPerTurn: Int,
    val buildTime: Int,  // Turns needed to build (0 = instant in initial phase)
    val minRange: Int = 0,  // Minimum range for attacks (0 = can attack adjacent)
    val isMine: Boolean = false  // Special flag for dwarven mine
) {
    SPIKE_TOWER("Spike Tower", baseCost = 10, baseDamage = 5, baseRange = 1, attackType = AttackType.MELEE, actionsPerTurn = 1, buildTime = 1),
    SPEAR_TOWER("Spear Tower", baseCost = 15, baseDamage = 8, baseRange = 2, attackType = AttackType.RANGED, actionsPerTurn = 1, buildTime = 1),
    BOW_TOWER("Bow Tower", baseCost = 20, baseDamage = 10, baseRange = 3, attackType = AttackType.RANGED, actionsPerTurn = 1, buildTime = 1),
    WIZARD_TOWER("Wizard Tower", baseCost = 50, baseDamage = 30, baseRange = 3, attackType = AttackType.AREA, actionsPerTurn = 1, buildTime = 2),
    ALCHEMY_TOWER("Alchemy Tower", baseCost = 40, baseDamage = 15, baseRange = 2, attackType = AttackType.LASTING, actionsPerTurn = 1, buildTime = 1),
    BALLISTA_TOWER("Ballista Tower", baseCost = 60, baseDamage = 50, baseRange = 5, attackType = AttackType.RANGED, actionsPerTurn = 1, buildTime = 2, minRange = 3),
    DWARVEN_MINE("Mine", baseCost = 100, baseDamage = 0, baseRange = 3, attackType = AttackType.NONE, actionsPerTurn = 0, buildTime = 3, isMine = true),
    DRAGONS_LAIR("Dragon's Lair", baseCost = 0, baseDamage = 0, baseRange = 0, attackType = AttackType.NONE, actionsPerTurn = 0, buildTime = 0)
}

enum class AttackType(val displayName: String ) {
    MELEE("Melee"),    // Single target, close range
    RANGED("Ranged"),   // Single target, long range
    AREA("Fireball"),      // Area of Effect - affects multiple enemies
    LASTING("Acid"),   // Damage over Time - lower damage but lasts multiple rounds
    NONE("Special")       // No attack capability (for mines and special structures)
}

data class Defender(
    val id: Int,
    val type: DefenderType,
    val position: MutableState<Position>,  // Changed to MutableState to support raft movement
    val level: MutableState<Int> = mutableStateOf(1),
    var dotRoundsRemaining: MutableMap<Int, Int> = mutableMapOf(), // attackerId -> rounds
    val buildTimeRemaining: MutableState<Int> = mutableStateOf(0),  // 0 = ready to use
    val actionsRemaining: MutableState<Int> = mutableStateOf(0),     // Actions left this turn
    val placedOnTurn: Int = 0,  // Track when tower was placed
    val hasBeenUsed: MutableState<Boolean> = mutableStateOf(false),  // Track if tower has attacked
    val isDisabled: MutableState<Boolean> = mutableStateOf(false), // Disabled by Red Witch
    val disabledTurnsRemaining: MutableState<Int> = mutableStateOf(0),
    // Mine-specific properties
    val coinsGenerated: MutableState<Int> = mutableStateOf(0),  // Total coins generated by this mine
    val canSell: Boolean = type != DefenderType.DRAGONS_LAIR,  // Can't sell dragon's lair
    val dragonId: MutableState<Int?> = mutableStateOf(null),  // Track which dragon came from this lair (for dragon's lair only)
    val dragonName: String? = null,  // Dragon's name (for dragon's lair only)
    // Wizard tower trap-specific properties
    val trapCooldownRemaining: MutableState<Int> = mutableStateOf(0),  // Turns until wizard can place another magical trap (level 10+)
    val hasShownMagicalTrapTutorial: MutableState<Boolean> = mutableStateOf(false),  // Track if tutorial was shown for this wizard
    val hasShownExtendedAreaTutorial: MutableState<Boolean> = mutableStateOf(false),  // Track if extended area tutorial was shown (level 20+)
    // Raft-specific properties
    val raftId: MutableState<Int?> = mutableStateOf(null)  // ID of the raft this tower is on (null if not on raft)
) {
    val damage: Int get() = type.baseDamage + (level.value - 1) * 5
    val range: Int get() {
        val baseCalculatedRange = type.baseRange + (level.value - 1) / 2
        // Pike (Spike) tower has a maximum range of 2 at level 5+
        if (type == DefenderType.SPIKE_TOWER && level.value >= 5) {
            return minOf(baseCalculatedRange, 2)
        }
        // Dwarven mine reach: 3 base, +1 every 5 levels, max 10
        if (type == DefenderType.DWARVEN_MINE) {
            val mineReach = 3 + (level.value / 5)
            return minOf(mineReach, 10)
        }
        return baseCalculatedRange
    }
    val upgradeCost: Int get() = type.baseCost * level.value
    val isReady: Boolean get() = buildTimeRemaining.value == 0
    
    // Calculate actions per turn based on level
    // Pike (Spike) tower gets +1 action per 5 levels (max 3 actions)
    // Dwarven mine gets 1 base action + 1 every 5 levels (starting at level 1: 1 action, level 5: 2 actions, etc.)
    val actionsPerTurnCalculated: Int get() {
        return if (type == DefenderType.SPIKE_TOWER) {
            val bonusActions = level.value / 5  // +1 at level 5, +2 at level 10, +3 at level 15, etc.
            minOf(type.actionsPerTurn + bonusActions, 3)  // Cap at 3 actions
        } else if (type == DefenderType.DWARVEN_MINE) {
            1 + (level.value / 5)  // 1 action at level 1-4, 2 at level 5-9, 3 at level 10-14, etc.
        } else {
            type.actionsPerTurn
        }
    }
    
    // Calculate total cost spent on this tower (base cost + all upgrade costs)
    // Level 1: baseCost (cost 50 to build)
    // Level 2: baseCost + upgradeCost for level 2 = baseCost + baseCost * 1 = baseCost * 2 (cost 50 + 50)
    // Level 3: above + upgradeCost for level 3 = baseCost * 2 + baseCost * 2 = baseCost * 4 (cost 50 + 50 + 100)
    val totalCost: Int get() {
        var total = type.baseCost
        for (lvl in 2..level.value) {
            total += type.baseCost * (lvl - 1)
        }
        return total
    }
    
    // Get the actual damage dealt by this tower
    // For LASTING towers, the actual damage is half the base damage
    // For mines, damage represents trap damage
    val actualDamage: Int get() = when (type.attackType) {
        AttackType.LASTING -> damage / 2
        else -> damage
    }
    
    // Calculate trap damage for dwarven mine: 10 base + 5 every 2 levels (starting at level 2)
    val trapDamage: Int get() {
        return if (type == DefenderType.DWARVEN_MINE) {
            10 + ((level.value / 2) * 5)  // Level 1: 10, Level 2: 15, Level 3: 15, Level 4: 20, etc.
        } else {
            0
        }
    }
    
    // Calculate LASTING duration for alchemy tower: 2 base turns + 1 extra per 5 levels (5, 10, 15, etc.)
    val dotDuration: Int get() {
        return if (type.attackType == AttackType.LASTING) {
            2 + (level.value / 5)  // Base 2 turns, +1 at level 5, +2 at level 10, +3 at level 15, etc.
        } else {
            0
        }
    }
    
    // Calculate the area effect radius for AREA and LASTING attacks
    // Base radius is 1 tile (immediate neighbors), at level 20+ it becomes 2 tiles
    val areaEffectRadius: Int get() {
        return if (type.attackType == AttackType.AREA || type.attackType == AttackType.LASTING) {
            if (level.value >= 20) 2 else 1
        } else {
            0
        }
    }
    
    // Check if the tower has extended area effect (level 20+)
    val hasExtendedAreaEffect: Boolean get() {
        return (type.attackType == AttackType.AREA || type.attackType == AttackType.LASTING) && level.value >= 20
    }
    
    fun canAttack(attacker: Attacker): Boolean {
        if (!isReady || actionsRemaining.value <= 0 || isDisabled.value) return false
        val distance = position.value.distanceTo(attacker.position.value)
        // Check both minimum and maximum range
        return distance >= type.minRange && distance <= range
    }
    
    fun resetActions() {
        if (isReady) {
            actionsRemaining.value = actionsPerTurnCalculated
            hasBeenUsed.value = false  // Reset usage tracking at start of new turn
        }
    }
}
